### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by markendley** [markendley/grndrgn#1]
But even when the total is over $132 the option of a $5 delivery is still there and pre-ticked - see chat image - when can I start adding images back to quire - this process is getting a bit too busy. The $5 delivery option should not be seen here - only the free shipping as the total is over $132

**Comment by markendley** [comment]
Yes but the user has the option of choose "free shipping".

Thats the way the standard checkout works with Woocommerce. You don't actually make the user to pay a checkout price they get give the options.

On the other hand I wrote a hack.

Take a look now, only option, how does that work the client?

**Comment by LaraStudioFriday** [comment]
Cool
