### ISSUE TITLE
Returning customer message

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/grndrgn#4]
This shows on a phone but not on laptop. Does this work? Should it be across all platforms?
![70882034_2404285492953612_7388497252781654016_n](https://user-images.githubusercontent.com/55725505/65477208-eb0f8880-dec8-11e9-85ce-bd59ab5337d0.jpg)
![71850283_2492074724242055_3519788817911382016_n](https://user-images.githubusercontent.com/55725505/65477215-f06cd300-dec8-11e9-8b3c-ba6cff7442a0.jpg)

**Comment by markendley** [comment]
Are you sure it doesn't show on laptops?

![Screen Shot 2019-09-24 at 12 48 09 pm](https://user-images.githubusercontent.com/6570606/65477402-98829c00-dec9-11e9-9619-437b41d53443.png)

**Comment by LaraStudioFriday** [comment]
Sorry it does if you click on proceed to checkout rather than buy now
